substitutions:
  board: az-delivery-devkit-v4 # Your esp32 board

  # Wifi credentials
  wifi_ssid: !secret wifi_ssid # Required to replace
  wifi_password: !secret wifi_password # Required to replace

  # OTA and API
  ota_password: !secret ota_password

esp32:
  board: $board
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_BT_ENABLED: y

esphome:
  name: blekeyboard
  includes:
    - "Esp32BleHidRemote.h"
    - "Esp32BleHidRemote.cpp"
  libraries:
    - https://github.com/fsievers22/esp32_ble_hid_remote/archive/refs/tags/v0.0.1-beta.zip

# Enable logging
logger:

# Enable OTA
ota:
  password: $ota_password

api:

# Enable WiFi
wifi:
  ssid: $wifi_ssid
  password: $wifi_password
  fast_connect: on

custom_component:
  - lambda: |-
      return {new Esp32BleHidRemote(App.get_name(), "ESPHome")};
    components:
      - id: ble_remote
switch:
  - platform: restart
    name: "Restart"

binary_sensor:
  - platform: custom
    lambda: |-
      auto remote = static_cast<Esp32BleHidRemote *>(ble_remote);
      return {remote->connected_binarysensor};
    binary_sensors:
      - name: "Connected"
        device_class: "connectivity"

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s