substitutions:
  board: az-delivery-devkit-v4 # Your esp32 board

  # Wifi credentials
  wifi_ssid: !secret wifi_ssid # Required to replace
  wifi_password: !secret wifi_password # Required to replace

  # OTA and API
  ota_password: !secret ota_password

esp32:
  board: $board
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_BT_ENABLED: y

esphome:
  name: blekeyboard
  platform: ESP32
  includes:
    - inc/keyboard.h
    - inc/keymap.h
  libraries:
    - https://github.com/T-vK/ESP32-BLE-Keyboard/releases/download/0.3.1-beta/ESP32-BLE-Keyboard.zip

# Enable logging
logger:

# Enable OTA
ota:
  password: $ota_password

# Enable WiFi
wifi:
  ssid: $wifi_ssid
  password: $wifi_password
  fast_connect: on

# Enable Home Assistant API
api:
  services:
    - service: send
      variables:
        message: string
        delay_ms: int
      then:
        lambda: |-
          (static_cast<Esp32BLEKeyboard *>(ble_keyboard))->release(message, delay_ms);
custom_component:
  - lambda: |-
      return {new Esp32BLEKeyboard(App.get_name(), "ESPHome")};
    components:
      - id: ble_keyboard
switch:
  - platform: restart
    name: "Restart"

binary_sensor:
  - platform: custom
    lambda: |-
      auto kbd = static_cast<Esp32BLEKeyboard *>(ble_keyboard);
      return {kbd->connected_binarysensor};
    binary_sensors:
      - name: "Connected"
        device_class: "connectivity"

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
  - platform: custom
    lambda: |-
      auto kbd = static_cast<Esp32BLEKeyboard *>(ble_keyboard);
      return {kbd->delay_sensor};
    sensors:
      - name: "Delay"
        unit_of_measurement: "ms"
        icon: "mdi:timer-outline"
        accuracy_decimals: 0